# для локального запуска/тестов

version: "3.8"
services:
  pg:
    image: "postgres:14"
    restart: "no"
    container_name: brendwall_db
    env_file:
      - .env
    ports:
      - "5432:5432"

  back:
    build: .
    container_name: brendwall_back
    restart: "no"
    env_file:
      - .env
    ports:
      - "8003:8003"
    volumes:
      - ./src:/brendwall_test
    depends_on:
      - pg
    command: /start